apiVersion: v1
kind: Pod
metadata:
  name: pod-https
  labels:
    app: https
spec:
  containers:
  - name: container
    image: nginx
    ports:
      - containerPort: 80
        name: http-web-svc

  terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: svc-https
spec:
  type: NodePort
  selector:
    app: https
  ports:
    - port: 80
      targetPort: http-web-svc
      nodePort: 30501
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: https
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nginx.jindol.com
    secretName: my-tls-secret
  rules:
  - host: nginx.jindol.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-https
            port:
              number: 80